version: 1.2
workflows:
  - subclass: WDL
    primaryDescriptorPath: /workflows/main.wdl
  - subclass: WDL
    primaryDescriptorPath: /workflows/rna_underlier.wdl
  - subclass: WDL
    primaryDescriptorPath: /workflows/q2_incidence.wdl
